trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    version: '17'
    jdkArchitecture: 'x64'
  displayName: 'Install Java 17'



- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'       # Gradle wrapper 파일 경로
    tasks: 'build'                    # 실행할 Gradle 태스크
    options: '--info --stacktrace --no-daemon'
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/**/*.xml'
    javaHomeOption: 'JDKVersion'      # JDK 버전 사용을 지정
    jdkVersionOption: '17'            # 사용할 JDK 버전
    jdkArchitectureOption: 'x64'      # JDK 아키텍처 설정
