trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    version: '17'
    jdkArchitecture: 'x64'
  displayName: 'Install Java 17'


- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    options: '--info --stacktrace --no-daemon'
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/**/*.xml'
